export const users = [
  {
    id: 1,
    name: "Doctor User",
    username: "dr.user@meditrust.demo",
    role: "Doctor",
    group: "EHR-Doctors",
    access: "Patient Records",
    mfa: "Required",
    riskPolicy: "CA001, CA002, CA003",
    status: "Protected",
    initials: "DU",
    color: "#3b82f6",
  },
  {
    id: 2,
    name: "Nurse User",
    username: "nurse.user@meditrust.demo",
    role: "Nurse",
    group: "EHR-Nurses",
    access: "Patient Records (Read)",
    mfa: "Required",
    riskPolicy: "CA001, CA002, CA003",
    status: "Protected",
    initials: "NU",
    color: "#10b981",
  },
  {
    id: 3,
    name: "Records Admin User",
    username: "records.admin@meditrust.demo",
    role: "Records Admin",
    group: "EHR-Records-Admins",
    access: "Admin Records",
    mfa: "Required",
    riskPolicy: "CA001, CA002, CA003",
    status: "Protected",
    initials: "RA",
    color: "#8b5cf6",
  },
  {
    id: 4,
    name: "IT Security Admin User",
    username: "it.security@meditrust.demo",
    role: "IT Security Admin",
    group: "EHR-IT-Security",
    access: "Monitoring / Logs",
    mfa: "Required (CA004)",
    riskPolicy: "CA001, CA002, CA003, CA004",
    status: "Protected",
    initials: "IS",
    color: "#f59e0b",
  },
  {
    id: 5,
    name: "Cloud Admin User",
    username: "cloud.admin@meditrust.demo",
    role: "Cloud Admin",
    group: "EHR-Cloud-Admins",
    access: "Azure Infrastructure",
    mfa: "Required (CA004)",
    riskPolicy: "CA001, CA002, CA003, CA004",
    status: "Protected",
    initials: "CA",
    color: "#0f172a",
  },
  {
    id: 6,
    name: "Vendor User",
    username: "vendor.user@meditrust.demo",
    role: "Vendor",
    group: "EHR-Vendors",
    access: "None — Restricted",
    mfa: "Required",
    riskPolicy: "CA001, CA002, CA003",
    status: "Restricted",
    initials: "VU",
    color: "#ef4444",
  },
  {
    id: 7,
    name: "Auditor User",
    username: "auditor.user@meditrust.demo",
    role: "Auditor",
    group: "EHR-Auditors",
    access: "Audit Evidence",
    mfa: "Required",
    riskPolicy: "CA001, CA002, CA003",
    status: "Protected",
    initials: "AU",
    color: "#6366f1",
  },
];

export const groups = [
  {
    id: "EHR-Doctors",
    members: 1,
    memberList: ["Doctor User"],
    access: "Patient Records",
    permission: "Read / Write",
  },
  {
    id: "EHR-Nurses",
    members: 1,
    memberList: ["Nurse User"],
    access: "Patient Records",
    permission: "Read Only",
  },
  {
    id: "EHR-Records-Admins",
    members: 1,
    memberList: ["Records Admin User"],
    access: "Admin Records",
    permission: "Read",
  },
  {
    id: "EHR-IT-Security",
    members: 1,
    memberList: ["IT Security Admin User"],
    access: "Monitoring / Audit Logs",
    permission: "Read",
  },
  {
    id: "EHR-Cloud-Admins",
    members: 1,
    memberList: ["Cloud Admin User"],
    access: "Azure Infrastructure",
    permission: "Admin",
  },
  {
    id: "EHR-Vendors",
    members: 1,
    memberList: ["Vendor User"],
    access: "None",
    permission: "None",
  },
  {
    id: "EHR-Auditors",
    members: 1,
    memberList: ["Auditor User"],
    access: "Audit Evidence",
    permission: "Read",
  },
];

export const policies = [
  {
    id: "CA001",
    name: "Require MFA for EHR Users",
    condition: "User is member of any EHR group",
    action: "Require MFA",
    target: "All EHR Groups",
    exception: "Emergency Access Account",
    purpose:
      "Ensures every simulated EHR user must complete multifactor authentication before accessing any resource. The emergency access account is excluded to preserve break-glass access.",
  },
  {
    id: "CA002",
    name: "Block High-Risk Sign-ins",
    condition: "Sign-in Risk: High",
    action: "Block Access",
    target: "All EHR Users",
    exception: "Emergency Admin",
    purpose:
      "When Microsoft Entra ID Protection detects a high-risk sign-in, access is immediately blocked regardless of credentials. This prevents access from compromised or suspicious sessions.",
  },
  {
    id: "CA003",
    name: "Require MFA for Medium-Risk Sign-ins",
    condition: "Sign-in Risk: Medium",
    action: "Require MFA",
    target: "All EHR Users",
    exception: "None",
    purpose:
      "Medium-risk sign-ins are not blocked outright but require an additional MFA challenge. This balances security with usability for legitimate users on unfamiliar devices.",
  },
  {
    id: "CA004",
    name: "Require MFA for Admin Roles",
    condition: "User in Cloud Admin or IT Security group",
    action: "Require MFA",
    target: "EHR-Cloud-Admins, EHR-IT-Security",
    exception: "Emergency Admin",
    purpose:
      "Administrative roles require MFA separately and independently of CA001. This ensures privileged users have an additional security gate beyond the standard EHR user policy.",
  },
];

export const resources = [
  {
    id: "patient-records",
    label: "patient-records",
    desc: "Contains simulated clinical records including patient files, lab results, and prescriptions.",
    files: ["patient_record_001.txt", "lab_result_001.txt", "prescription_001.txt"],
    privacy: "Private",
  },
  {
    id: "admin-records",
    label: "admin-records",
    desc: "Contains simulated administrative records including appointment and billing data.",
    files: ["appointment_record_001.txt", "billing_summary_001.txt"],
    privacy: "Private",
  },
  {
    id: "audit-evidence",
    label: "audit-evidence",
    desc: "Contains simulated audit and compliance files for governance review.",
    files: ["access_log_001.txt", "policy_review_001.txt", "compliance_report_001.txt"],
    privacy: "Private",
  },
];

export const permissionMatrix: Record<string, Record<string, string>> = {
  Doctor:        { "patient-records": "RW", "admin-records": "—", "audit-evidence": "—" },
  Nurse:         { "patient-records": "R",  "admin-records": "—", "audit-evidence": "—" },
  "Records Admin":{ "patient-records": "—", "admin-records": "R", "audit-evidence": "—" },
  Auditor:       { "patient-records": "—",  "admin-records": "—", "audit-evidence": "R" },
  Vendor:        { "patient-records": "—",  "admin-records": "—", "audit-evidence": "—" },
  "Cloud Admin": { "patient-records": "Admin","admin-records": "Admin","audit-evidence": "Admin" },
  "IT Security": { "patient-records": "—",  "admin-records": "—", "audit-evidence": "R" },
};

export const permissions: Record<string, Record<string, string[]>> = {
  "Doctor User":            { "patient-records": ["read","write"], "admin-records": [], "audit-evidence": [] },
  "Nurse User":             { "patient-records": ["read"],         "admin-records": [], "audit-evidence": [] },
  "Records Admin User":     { "patient-records": [],               "admin-records": ["read"], "audit-evidence": [] },
  "Auditor User":           { "patient-records": [],               "admin-records": [], "audit-evidence": ["read"] },
  "Vendor User":            { "patient-records": [],               "admin-records": [], "audit-evidence": [] },
  "Cloud Admin User":       { "patient-records": ["read","write","delete","manage"], "admin-records": ["read","write","delete","manage"], "audit-evidence": ["read","write","delete","manage"] },
  "IT Security Admin User": { "patient-records": [],               "admin-records": [], "audit-evidence": ["read"] },
};

export const activity = [
  { id: 1,  time: "09:42", user: "Vendor User",         event: "Access Attempt",   resource: "Patient Records", risk: "Low",    result: "DENIED",  type: "denied"  },
  { id: 2,  time: "09:38", user: "Nurse User",          event: "Read",             resource: "Patient Records", risk: "Low",    result: "ALLOWED", type: "allowed" },
  { id: 3,  time: "09:31", user: "Unknown",             event: "Sign-in Attempt",  resource: "Azure Portal",    risk: "High",   result: "BLOCKED", type: "blocked" },
  { id: 4,  time: "09:20", user: "Doctor User",         event: "Update Record",    resource: "Patient Records", risk: "Low",    result: "ALLOWED", type: "allowed" },
  { id: 5,  time: "09:15", user: "Nurse User",          event: "MFA Challenge",    resource: "Azure Portal",    risk: "Medium", result: "MFA REQ", type: "mfa"     },
  { id: 6,  time: "09:08", user: "Auditor User",        event: "Read",             resource: "Audit Evidence",  risk: "Low",    result: "ALLOWED", type: "allowed" },
  { id: 7,  time: "08:55", user: "Records Admin User",  event: "Read",             resource: "Admin Records",   risk: "Low",    result: "ALLOWED", type: "allowed" },
  { id: 8,  time: "08:47", user: "Vendor User",         event: "Access Attempt",   resource: "Admin Records",   risk: "Low",    result: "DENIED",  type: "denied"  },
  { id: 9,  time: "08:34", user: "Cloud Admin User",    event: "MFA Verification", resource: "Azure Portal",    risk: "Low",    result: "ALLOWED", type: "allowed" },
  { id: 10, time: "08:20", user: "IT Security Admin",   event: "Log Review",       resource: "Audit Evidence",  risk: "Low",    result: "ALLOWED", type: "allowed" },
  { id: 11, time: "08:10", user: "Unknown",             event: "Sign-in Attempt",  resource: "Azure Portal",    risk: "High",   result: "BLOCKED", type: "blocked" },
  { id: 12, time: "07:58", user: "Doctor User",         event: "Authenticated",    resource: "Azure Portal",    risk: "Low",    result: "ALLOWED", type: "allowed" },
];

export const flowSteps = [
  { label: "User",       icon: "👤", tooltip: "Who is making this request?" },
  { label: "Identity",   icon: "🪪", tooltip: "Entra ID verifies the user's identity and security group membership." },
  { label: "MFA",        icon: "🔐", tooltip: "MFA is required for all EHR users (CA001). Admin roles have an extra gate (CA004)." },
  { label: "Risk Check", icon: "⚠️", tooltip: "High-risk sign-ins are blocked (CA002). Medium-risk require MFA (CA003)." },
  { label: "Role",       icon: "🎭", tooltip: "The user's role comes from their Entra security group." },
  { label: "Permission", icon: "🔑", tooltip: "Azure RBAC checks whether this role has the required permission on this resource." },
  { label: "Resource",   icon: "🗄️", tooltip: "The target is a private Azure storage container." },
  { label: "Decision",   icon: "⚖️", tooltip: "All checks complete — access is allowed or denied and the event is logged." },
];